version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: irisuser
      POSTGRES_PASSWORD: irispass
      POSTGRES_DB: irisdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: ./app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:
